project_id = "vtrczddwhahqfitaqona"

[functions.parse-cv]
verify_jwt = false

[functions.recommend]
verify_jwt = false

[functions.save-submission]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.seed-programmes]
verify_jwt = false